### ISSUE TITLE
KeyError: 'meta'

### ISSUE THREAD

**Issue by drnextgis** [sat-utils/sat-search#80]
Trying to run this simple query but it raises an error:

```
$ sat-search search --intersects catalunyacv.geojson --datetime "2019-04-01/2019-05-01" --found
Traceback (most recent call last):
  File "/home/denis/satellogic/env-shub/bin/sat-search", line 11, in <module>
    sys.exit(cli())
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/satsearch/main.py", line 65, in cli
    main(**kwargs)
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/satsearch/main.py", line 20, in main
    num = search.found()
  File "/home/denis/satellogic/env-shub/lib/python3.6/site-packages/satsearch/search.py", line 75, in found
    return results['meta']['found']
KeyError: 'meta'
```

**Comment by samsammurphy** [comment]
I just hit this too.. What is weird is that the code was working a few hours ago.. Is this an intermittent problem?

This [query here](https://github.com/sat-utils/sat-search/blob/d81e4774a41990b73b55db4b1e05b21062dd957c/satsearch/search.py#L74)
`results = self.query(**kwargs)`

Is throwing a 500
`{'code': 500, 'description': "Cannot read property 'search' of undefined"}`

@matthewhanson :wave: do you know what "Cannot read property 'search' of undefined" might mean?

**Comment by samsammurphy** [comment]
it is now working again ¯\_(ツ)_/¯

**Comment by JanisGailis** [comment]
For posterity, I got this error when using a `geojson` file the API didn't like. Using a sanitized version of the same file didn't produce the error.

One can examine the exact cause of an error like this by printing out the `result` itself and examining it.
