### ISSUE TITLE
download sentinel2 from cli (KeyError: 'href')

### ISSUE THREAD

**Issue by samsammurphy** [sat-utils/sat-search#82]
When using the cli to search by ID and then download a Sentinel2 granule  by ID and I hit a keyword error.

**Stacktrace**

```
1 items found
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/satstac/item.py", line 146, in download
    ext = os.path.splitext(asset['href'])[1]
KeyError: 'href'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sat-search", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/satsearch/main.py", line 65, in cli
    main(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/satsearch/main.py", line 48, in main
    items.download(key=key, path=config.DATADIR, filename=config.FILENAME, requestor_pays=requestor_pays)
  File "/usr/local/lib/python3.6/dist-packages/satstac/items.py", line 141, in download
    fname = i.download(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/satstac/item.py", line 154, in download
    logger.error('Unable to download %s: %s' % (asset['href'], str(e)))
KeyError: 'href'
```

**Steps to reproduce**

```
sat-search search --collection sentinel-2-l1c --ids S2B_15SUB_20180417_0 --save /tmp/test.geojson

sat-search load /tmp/test.geojson --download swir16 swir22 --datadir /tmp --requestor-pays
```

**Comment by matthewhanson** [comment]
Thx @samsammurphy , we know for certain the ID exists right?   Is it for any Sentinel scene?  Any idea if this happens with Landsat as well?

The way sat-search searches by IDs will change with STAC 0.7+, because the API supports ids directly (sat-search currently just loops through the ids provided and fetches each record as a separate request).

So this update will happen sometime during July.

**Comment by samsammurphy** [comment]
Hi @matthewhanson. Yep the ID for sure [exists](https://sentinel-stac.s3.amazonaws.com/index.html#/item/Gbb7Xx6cfk7aogdaht8NQUX6XJEmJMVLmEdCy/Q86P27jAfP31GKZ6No1wnhS1vqxU2LMJPBbKsxfRo/8mTbKdDz4L5eY1TQyXE2EMXZbG1krTQyvBf5UMS75Mx9/CWprNh2bo2T9zC6euqZeRo354kCYa3aJTyr6fxdQnp7yDHyX/5dih5PTze13WkMuKfMuForgfkP12fkTcw3sqZJX4SBgacNMsWuQ7rLkrnUaPzv9VUGPioJaGQQsUJmCYD)

I re-ran the code and got a new stacktrace error (below). 

I also tested this with a new Sentinel ID (S2A_9VXL_20160131_0) and Landsat ID (LC80100202015002LGN00) and got the same error. Those new IDs are from exploring the [Sentinel2 STAC](https://sentinel-stac.s3.amazonaws.com/index.html#/) and the[ Landsat 8 STAC](https://landsat-stac.s3.amazonaws.com/index.html#/).

There is a good chance that the STAC 0.7 update will fix this issue.

 ```
 File "/usr/local/bin/sat-search", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/satsearch/main.py", line 65, in cli
    main(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/satsearch/main.py", line 23, in main
    items = search.items()
  File "/usr/local/lib/python3.6/dist-packages/satsearch/search.py", line 113, in items
    return self.items_by_id(self.kwargs['ids'], col)
  File "/usr/local/lib/python3.6/dist-packages/satsearch/search.py", line 104, in items_by_id
    return Items(items, collections=[col])
  File "/usr/local/lib/python3.6/dist-packages/satstac/items.py", line 17, in __init__
    cols = {c.id: c for c in self._collections}
  File "/usr/local/lib/python3.6/dist-packages/satstac/items.py", line 17, in <dictcomp>
    cols = {c.id: c for c in self._collections}
  File "/usr/local/lib/python3.6/dist-packages/satstac/thing.py", line 64, in id
    return self.data['id']
KeyError: 'id'


```
